// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCapCYvAfS6bWtsUFA1FMsYO_YfsvAAGWg',
    appId: '1:538330805104:web:f6bf1fdae983ae8fe2d5b5',
    messagingSenderId: '538330805104',
    projectId: 'fill-d-db8f7',
    authDomain: 'fill-d-db8f7.firebaseapp.com',
    databaseURL: 'https://fill-d-db8f7-default-rtdb.firebaseio.com',
    storageBucket: 'fill-d-db8f7.appspot.com',
    measurementId: 'G-X07X44JMGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5cFO7zVS8Vx4xxpMZg7YlZ0vzh5uawcE',
    appId: '1:538330805104:android:e4dc1abedd9b9515e2d5b5',
    messagingSenderId: '538330805104',
    projectId: 'fill-d-db8f7',
    databaseURL: 'https://fill-d-db8f7-default-rtdb.firebaseio.com',
    storageBucket: 'fill-d-db8f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeMKtQ8nlMnouNCvAt6JfHHGSC7bvRjKg',
    appId: '1:538330805104:ios:be22cb01d88402a4e2d5b5',
    messagingSenderId: '538330805104',
    projectId: 'fill-d-db8f7',
    databaseURL: 'https://fill-d-db8f7-default-rtdb.firebaseio.com',
    storageBucket: 'fill-d-db8f7.appspot.com',
    androidClientId: '538330805104-1sq6iqj5dgfg90cca0dhqt3bmdr4cs8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.filldadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeMKtQ8nlMnouNCvAt6JfHHGSC7bvRjKg',
    appId: '1:538330805104:ios:71bc14306111f47de2d5b5',
    messagingSenderId: '538330805104',
    projectId: 'fill-d-db8f7',
    databaseURL: 'https://fill-d-db8f7-default-rtdb.firebaseio.com',
    storageBucket: 'fill-d-db8f7.appspot.com',
    androidClientId: '538330805104-1sq6iqj5dgfg90cca0dhqt3bmdr4cs8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.filldadmin.RunnerTests',
  );
}
